kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "csi-libvirt.fullname" . }}-node
  labels:
    {{- include "csi-libvirt.labels" . | nindent 4 }}
    tier: node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      {{- include "csi-libvirt.selectorLabels" . | nindent 6 }}
      tier: node
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: csi-libvirt-plugin
        {{- with .Values.node.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "csi-libvirt.selectorLabels" . | nindent 8 }}
        tier: node
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.extraSpec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      priorityClassName: system-node-critical
      serviceAccount: csi-libvirt-node-sa
      hostNetwork: true
      containers:
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/lu.lxc.csi.libvirt /registration/lu.lxc.csi.libvirt-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/lu.lxc.csi.libvirt/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
        - name: csi-libvirt-plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - "node"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: CSI_NODE_MACHINEIDFILE
              value: {{ .Values.node.machineIdFile }}
          {{- with .Values.node.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: "IfNotPresent"
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: machine-id
              mountPath: {{ .Values.node.machineIdFile }}
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: udev-data-dir
              mountPath: /run/udev/data
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: machine-id
          hostPath:
            path: {{ .Values.node.machineIdFile }}
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lu.lxc.csi.libvirt
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        - name: udev-data-dir
          hostPath:
            path: /run/udev/data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-libvirt-node-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-libvirt-node-driver-registrar-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-libvirt-node-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: csi-libvirt-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-libvirt-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io