image:
  repository: luxchan/libvirt-csi
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
fullnameOverride: ""
nameOverride: ""

controller:
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes: []
  volumeMounts: []
  env: []

node:
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: []
  machineIdFile: /etc/machine-id
